name: Code Analysis
 
on: 
    push:
        branches: [master]
 
jobs:
  resharper:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: install resharper
        run: dotnet tool install -g JetBrains.ReSharper.GlobalTools
        
      - name: run resharper
        run: jb inspectcode OddOrEven.sln -o=report.xml
